### PR TITLE
[client] Avoid deadlock when auto connect and early exit

### LINKED ISSUE #2527: Deadlock in latest master build when starting service
**Describe the problem**

Following PR created a deadlock
https://github.com/netbirdio/netbird/commit/13e7198046a0d73a9cd91bf8e063fafb3d41885c

Specifically this [line](https://github.com/netbirdio/netbird/commit/13e7198046a0d73a9cd91bf8e063fafb3d41885c#diff-b9a524a16fa54801148c3bf6f07149721310a5d097f234e839466a751ca900d8R151) and so this never gets executed https://github.com/netbirdio/netbird/blob/main/client/cmd/service_controller.go#L62 because of of the deadlock

**To Reproduce**

Not sure because it happens at various times, and independent of the flag

**Expected behavior**
GRPC Socket to be responsive and status cmd to work

**Are you using NetBird Cloud?**
no 

Please specify whether you use NetBird Cloud or self-host NetBird's control plane.

**NetBird version**

master

**NetBird status -dA output:**

NA

I did builds where I remove the wait, and sure enough `netbird status` would be functional again. On non working instances the log file was missing 
```
started daemon server
```

### PR DESCRIPTION
**Pull request by mlsmaycon**
## Issue ticket number and link
resolves #2527 
### Checklist
- [x] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by hurricanehrndz** [comment]
Going to test this patch out

**Comment by hurricanehrndz** [comment]
Nice fix!

File: client/server/server.go [hunk 1]
```diff
@@ -587,13 +585,22 @@ func (s *Server) Up(callerCtx context.Context, _ *proto.UpRequest) (*proto.UpRes
...
-	runningWg.Wait()
+	runningChan := make(chan error)
+	go s.connectWithRetryRuns(ctx, s.config, s.statusRecorder, runningChan)
 
-	return &proto.UpResponse{}, nil
+	for {
+		select {
+		case err := <-runningChan:
+			if err != nil {
+				log.Debugf("waiting for engine to become ready failed: %s", err)
```
Comment (lixmal) [inline client/server/server.go:595]: Shouldn't this return the error?

Comment (pascal-fischer) [reply client/server/server.go:595]: No we do have the silent retry. If I would return this would break. I am just gonna log here. This is just a channel for us to get the errors outside.

Comment (lixmal) [reply client/server/server.go:595]: Got it

**Review by bcmmbaga — APPROVED** [review]
