### PR TITLE
Routes is a map, employing safe read/writes ops

### LINKED ISSUE #1759: fatal error: concurrent map writes introduced with  https://github.com/netbirdio/netbird/commit/4a1aee1ae0188191fc97bb732727820260770d7c
**Describe the problem**

fatal error: concurrent map writes introduced with  https://github.com/netbirdio/netbird/commit/4a1aee1ae0188191fc97bb732727820260770d7c

Specifically lines such as [these](https://github.com/netbirdio/netbird/commit/4a1aee1ae0188191fc97bb732727820260770d7c#diff-67387c2b097eeb87387ab2575884677a2f9ee1c53b9e8674dcfa4936463c23f9R242), Routes is a map with no mutex locking, but adding a mutex to the struct directly will not work. At least that is my impression because  the struct is copied and updated in several places

**To Reproduce**
Run any version of netbird with patch https://github.com/netbirdio/netbird/commit/4a1aee1ae0188191fc97bb732727820260770d7c

Start netbird service on macos
Connect
Watch service restart

**Expected behavior**
No fatal crash

**Are you using NetBird Cloud?**

Please specify whether you use NetBird Cloud or self-host NetBird's control plane.

**NetBird version**

`netbird version`
0.26.4
**NetBird status -d output:**
NA
If applicable, add the `netbird status -d' command output.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by hurricanehrndz**
Adding a mutex to the struct although the norm, could not be used due to the state being copied around. Fixes #1759 

### Checklist
- [x ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

File: client/internal/routemanager/client.go [hunk 1]
```diff
@@ -246,10 +246,8 @@ func (c *clientNetwork) recalculateRouteAndUpdatePeerAndSystem() error {
 	if err != nil {
 		log.Errorf("Failed to get peer state: %v", err)
 	} else {
-		if state.Routes == nil {
-			state.Routes = map[string]struct{}{}
-		}
-		state.Routes[c.network.String()] = struct{}{}
+		//TODO: hurricanehrndz
```
Comment (lixmal) [inline client/internal/routemanager/client.go]: What's the todo here?

File: client/internal/peer/status.go [hunk 2]
```diff
@@ -30,7 +31,38 @@ type State struct {
...
+// DeleteRoute removes a route from the network amp
+func (s *State) DeleteRoute(network string) {
+    s.Mux.Lock()
+	delete(s.routes, network)
+    s.Mux.Unlock()
+}
+
+// GetRoutes return routes map
+func (s *State) GetRoutes() map[string]struct{} {
+    s.Mux.Lock()
```
Comment (lixmal) [inline client/internal/peer/status.go]: I believe this should be a `RLock()`

**Review by lixmal — CHANGES_REQUESTED** [review]
Thank you for your contribution @hurricanehrndz. Could you also fix the tests please?

**Comment by hurricanehrndz** [comment]
> Thank you for your contribution @hurricanehrndz. Could you also fix the tests please?

I can definitely take a look at this weekend

**Comment by hurricanehrndz** [comment]
@lixmal PR should be good now, squashed all my commits and cleaned up the tests and some formatting issues I had introduce

**Comment by hurricanehrndz** [comment]
@lixmal is there anything you require of me?

**Review by mlsmaycon — APPROVED** [review]
Approved. 

Thanks @hurricanehrndz
